CONTAINER AINODE_LATLONGSTEREO
{
	NAME ainode_LatLongStereo;

	INCLUDE GVbase;

	GROUP C4DAI_LATLONGSTEREO_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_LATLONGSTEREO_CAMERA {}
		AIPARAM C4DAIP_LATLONGSTEREO_FOV_VERT_ANGLE {}
		AIPARAM C4DAIP_LATLONGSTEREO_FOV_HORIZ_ANGLE {}
		AIPARAM C4DAIP_LATLONGSTEREO_PARALLAX_DISTANCE {}
		AIPARAM C4DAIP_LATLONGSTEREO_SEPARATION {}
		AIPARAM C4DAIP_LATLONGSTEREO_ZENITH_MODE {}
		AIPARAM C4DAIP_LATLONGSTEREO_SEPARATION_MAP {}
		//AIPARAM C4DAIP_LATLONGSTEREO_HEAD_TURN_MAP {}
		AIPARAM C4DAIP_LATLONGSTEREO_HEAD_TILT_MAP {}
		AIPARAM C4DAIP_LATLONGSTEREO_FLIP_RAY_X {}
		AIPARAM C4DAIP_LATLONGSTEREO_FLIP_RAY_Y {}
	}
}

