CONTAINER AINODE_DOMEMASTERSTEREO
{
	NAME ainode_DomemasterStereo;

	INCLUDE GVbase;

	GROUP C4DAI_DOMEMASTERSTEREO_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_DOMEMASTERSTEREO_CAMERA {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_FOV_ANGLE {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_ZERO_PARALLAX_SPHERE {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_SEPARATION {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_FORWARD_TILT {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_TILT_COMPENSATION {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_VERTICAL_MODE {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_SEPARATION_MAP {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_HEAD_TURN_MAP {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_HEAD_TILT_MAP {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_FLIP_RAY_X {}
		AIPARAM C4DAIP_DOMEMASTERSTEREO_FLIP_RAY_Y {}
	}
}

