CONTAINER AITAG_DOMEMASTERWXH
{
   NAME AiTagDomemasterWxH;

   GROUP C4DAI_DOMEMASTERWXH_MAIN_GRP
   {
      DEFAULT 1;
      
      GROUP C4DAI_DOMEMASTERWXH_SHADER_GRP
      {
        DEFAULT 1;
      
        AIPARAM C4DAIP_DOMEMASTERWXH_DIAMETER {}
        AIPARAM C4DAIP_DOMEMASTERWXH_HEIGHT {}
      }
      GROUP C4DAI_DOMEMASTERWXH_FLIP_GRP
      {
        AIPARAM C4DAIP_DOMEMASTERWXH_FLIP_RAY_X {}
        AIPARAM C4DAIP_DOMEMASTERWXH_FLIP_RAY_Y {}
      }
      GROUP C4DAI_DOMEMASTERWXH_EXTRAS_GRP
      {
        AIPARAM C4DAIP_DOMEMASTERWXH_EXPOSURE {}
        AIPARAM C4DAIP_DOMEMASTERWXH_FILTERMAP {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_DOMEMASTERWXH_ROLLING_SHUTTER {}
        AIPARAM C4DAIP_DOMEMASTERWXH_ROLLING_SHUTTER_DURATION {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_DOMEMASTERWXH_SHUTTER_START {}
        AIPARAM C4DAIP_DOMEMASTERWXH_SHUTTER_END {}
        AIPARAM C4DAIP_DOMEMASTERWXH_SHUTTER_TYPE {}
        AIPARAM C4DAIP_DOMEMASTERWXH_SHUTTER_CURVE {} 
      }
   }
}

