CONTAINER AINODE_DOMEMASTERWXH
{
	NAME ainode_DomemasterWxH;

	INCLUDE GVbase;

	GROUP C4DAI_DOMEMASTERWXH_MAIN_GRP
	{
		DEFAULT 1;

		AIPARAM C4DAIP_DOMEMASTERWXH_DIAMETER {}
		AIPARAM C4DAIP_DOMEMASTERWXH_HEIGHT {}
		//AIPARAM C4DAIP_DOMEMASTERWXH_VIEW_OFFSET {}
		AIPARAM C4DAIP_DOMEMASTERWXH_FLIP_RAY_X {}
		AIPARAM C4DAIP_DOMEMASTERWXH_FLIP_RAY_Y {}
	}
}

