# Mac OS X - LatLong_Stereo Mental Ray Shader Makefile
# by Andrew Hazelden  andrew@andrewhazelden.com
# http://www.andrewhazelden.com

# You can compile this file from the command line using:
# make -f Makefile.osx

# You can install the files using the command
# sudo make -f Makefile.osx install

CC = gcc

#MAYA_DIR=/Applications/Autodesk/maya2011
#MAYA_DIR=/Applications/Autodesk/maya2012
#MAYA_DIR=/Applications/Autodesk/maya2013
#MAYA_DIR=/Applications/Autodesk/mentalrayForMaya2014
MAYA_DIR=/Applications/Autodesk/mentalrayForMaya2015

DOMEMASTER_DIR=/Applications/Domemaster3D/maya/shaders

# Maya 2012's mental ray directory:
#MENTALRAY_DEV_DIR=/devkit/mentalray/include

# Maya 2013's mental ray directory:
#MENTALRAY_DEV_DIR=/mentalray/devkit/include

# Maya 2014/2015's mental ray devkit directory:
MENTALRAY_DEV_DIR=/devkit/include

INC = -I$(MAYA_DIR)$(MENTALRAY_DEV_DIR)
LIB = 
LIB_STATIC = 
CFLAGS = -c -O3 -fPIC -DBIT64 -dynamic -fno-common
LIBTOOL = libtool
LDEXECFLAGS=-macosx_version_min 10.6

OBJS = LatLong_Stereo.o 
SRCS = LatLong_Stereo.c

all: LatLong_Stereo.dylib 

$(OBJS): 
	$(CC) $(CFLAGS) $(INC) $(LIB) $(SRCS) $(LIB_STATIC)

LatLong_Stereo.dylib : $(OBJS) 
	$(LIBTOOL) -flat_namespace -undefined suppress -dynamic $(LDEXECFLAGS) -o LatLong_Stereo.dylib  $(OBJS)

clean: 
	rm -rf $(OBJS) 
	rm -rf LatLong_Stereo.dylib

install:	
	# MR Shaders Folder
	cp ./LatLong_Stereo.dylib $(MAYA_DIR)/mentalray/shaders
	cp ./LatLong_Stereo.mi $(MAYA_DIR)/mentalray/shaders/include
  
  # Domemaster3D Shaders Folder
	cp ./LatLong_Stereo.dylib $(DOMEMASTER_DIR)
	cp ./LatLong_Stereo.mi $(DOMEMASTER_DIR )/include


go: clean all install
