CONTAINER AITAG_DOMEMASTERSTEREO
{
   NAME AiTagDomemasterStereo;

   GROUP C4DAI_DOMEMASTERSTEREO_MAIN_GRP
   {
      DEFAULT 1;

      GROUP C4DAI_DOMEMASTERSTEREO_SHADER_GRP
      {
        DEFAULT 1;
      
        AIPARAM C4DAIP_DOMEMASTERSTEREO_CAMERA {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_FOV_ANGLE {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_ZERO_PARALLAX_SPHERE {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_FORWARD_TILT {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_SEPARATION {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_TILT_COMPENSATION {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_VERTICAL_MODE {}
      }
      GROUP C4DAI_DOMEMASTERSTEREO_CUSTOM_MAPS_GRP
      {
        DEFAULT 1;
        
        AIPARAM C4DAIP_DOMEMASTERSTEREO_SEPARATION_MAP {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_HEAD_TURN_MAP {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_HEAD_TILT_MAP {}
      }
      GROUP C4DAI_DOMEMASTERSTEREO_FLIP_GRP
      {
        DEFAULT 1;
      
        AIPARAM C4DAIP_DOMEMASTERSTEREO_FLIP_RAY_X {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_FLIP_RAY_Y {}
      }
      
      GROUP C4DAI_DOMEMASTERSTEREO_EXTRAS_GRP
      {
        DEFAULT 1;
      
        AIPARAM C4DAIP_DOMEMASTERSTEREO_EXPOSURE {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_FILTERMAP {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_ROLLING_SHUTTER {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_ROLLING_SHUTTER_DURATION {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_SHUTTER_START {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_SHUTTER_END {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_SHUTTER_TYPE {}
        AIPARAM C4DAIP_DOMEMASTERSTEREO_SHUTTER_CURVE {} 
      }
   }
}

