CONTAINER AITAG_LATLONGSTEREO
{
   NAME AiTagLatLongStereo;

   GROUP C4DAI_LATLONGSTEREO_MAIN_GRP
   {
      DEFAULT 1;
      
      GROUP C4DAI_LATLONGSTEREO_SHADER_GRP
      {
        DEFAULT 1;
      
        AIPARAM C4DAIP_LATLONGSTEREO_CAMERA {}
        AIPARAM C4DAIP_LATLONGSTEREO_FOV_VERT_ANGLE {}
        AIPARAM C4DAIP_LATLONGSTEREO_FOV_HORIZ_ANGLE {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_LATLONGSTEREO_PARALLAX_DISTANCE {}
        AIPARAM C4DAIP_LATLONGSTEREO_SEPARATION {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_LATLONGSTEREO_ZENITH_MODE {}
      }
      GROUP C4DAI_LATLONGSTEREO_CUSTOM_MAPS_GRP
      {
        DEFAULT 1;
        
        AIPARAM C4DAIP_LATLONGSTEREO_SEPARATION_MAP {}
        AIPARAM C4DAIP_LATLONGSTEREO_HEAD_TILT_MAP {}
      }
      GROUP C4DAI_LATLONGSTEREO_FLIP_GRP
      {
        DEFAULT 1;
        AIPARAM C4DAIP_LATLONGSTEREO_FLIP_RAY_X {}
        AIPARAM C4DAIP_LATLONGSTEREO_FLIP_RAY_Y {}
      }
      GROUP C4DAI_LATLONGSTEREO_EXTRAS_GRP
      {
        DEFAULT 1;
      
        AIPARAM C4DAIP_LATLONGSTEREO_EXPOSURE {}
        AIPARAM C4DAIP_LATLONGSTEREO_FILTERMAP {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_LATLONGSTEREO_ROLLING_SHUTTER {}
        AIPARAM C4DAIP_LATLONGSTEREO_ROLLING_SHUTTER_DURATION {}
        SEPARATOR {LINE;}
        AIPARAM C4DAIP_LATLONGSTEREO_SHUTTER_START {}
        AIPARAM C4DAIP_LATLONGSTEREO_SHUTTER_END {}
        AIPARAM C4DAIP_LATLONGSTEREO_SHUTTER_TYPE {}
        AIPARAM C4DAIP_LATLONGSTEREO_SHUTTER_CURVE {}
      }
   }
}

